# Generated by Django 4.2 on 2023-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sopapp', '0004_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='breaks',
            field=models.CharField(default=' ', max_length=400),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_chars',
            field=models.CharField(default=' ', max_length=400),
        ),
    ]
